import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import { usageFixture, databaseOne } from '../cloud/usage-fixture.mjs';
import { fakeToken } from '../cloud/connections-fixture.mjs';
import { origin } from '../cloud/admin-fixture.mjs';

const { f, state } = await usageFixture(); let browser;
try {
  let token = f.jwt(); const session = { token, headers: { 'x-csrf-token': (await f.call('/api/admin/state', { token })).json().csrf } };
  const add = async () => f.call('/api/admin/connections', { ...session, body: { action: 'connect', id: crypto.randomUUID(), name: '容量规划', provider: 'cloudflare', accountId: '', token: fakeToken } });
  assert.equal((await add()).status, 200); assert.equal((await add()).status, 200, 'A second credential for the same accounts is intentional');
  const writes = [], reads = [], errors = [], directory = process.env.UI_EVIDENCE_DIR ?? 'test-results';
  await mkdir(directory, { recursive: true });
  browser = await chromium.launch(process.env.CHROME_PATH ? { executablePath: process.env.CHROME_PATH } : { channel: 'chrome' });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
  await context.route('**/*', async route => {
    const request = route.request(); assert.equal(new URL(request.url()).origin, origin);
    const body = request.postData() ? request.postDataJSON() : null;
    if (body) (['inventory', 'usage'].includes(body.action) ? reads : writes).push(body.action);
    const response = await f.mf.dispatchFetch(request.url(), { method: request.method(), headers: { ...request.headers(), 'cf-access-jwt-assertion': token }, ...(body ? { body: request.postData() } : {}) });
    await route.fulfill({ status: response.status, headers: Object.fromEntries(response.headers), body: Buffer.from(await response.arrayBuffer()) });
  });
  const page = await context.newPage(); page.on('pageerror', error => errors.push(error.message));
  const ready = () => page.waitForFunction(() => !document.getElementById('resource-fields').disabled && document.getElementById('resource-notice').textContent === '');
  const accountA = 'a'.repeat(32), accountB = 'b'.repeat(32);
  const group = (kind, account = accountA) => page.locator(`.inventory-group[data-kind="${kind}"][data-account="${account}"]`);
  const open = async locator => { if (!(await locator.evaluate(element => element.open))) await locator.locator(':scope > summary').click(); };
  await page.goto(origin + '/resources'); await ready();
  assert.equal(await page.locator('.resource-node[data-account]:not(.inventory-group)').count(), 2, 'Duplicate keys share two account nodes');
  assert.equal(await group('d1').evaluate(element => element.open), false);
  assert.match(await group('d1').locator(':scope > summary').textContent(), /6 GB \/ 5 GB/);
  assert.match(await group('d1').locator(':scope > summary').textContent(), /超出 1 GB/);
  assert.equal(await group('d1').locator('[data-detail]').count(), 2);
  assert.equal(await page.locator('[data-node-key="brand/cloudflare"] > summary [data-metric="d1/storage"] [role=progressbar]').count(), 1);
  assert.match(await page.locator('[data-node-key="brand/cloudflare"] > summary [data-metric="d1/storage"]').textContent(), /7 GB \/ 10 GB/);
  await page.screenshot({ path: join(directory, 'usage-account-desktop.png'), fullPage: true });
  await open(group('d1')); const instance = group('d1').locator(`[data-detail="${databaseOne}"]`); await instance.click();
  await page.locator('#resource-detail-dialog[open]').waitFor(); const accountDetail = await page.locator('#resource-detail').textContent();
  assert.match(accountDetail, /4 GB/); assert.match(accountDetail, /账户共享套餐额度5 GB/);
  await page.keyboard.press('Escape'); assert.equal(await instance.evaluate(element => element === document.activeElement), true);
  const readCount = reads.length; await page.locator('#resource-view-kind').click();
  assert.equal(await page.locator('#resource-view-kind').getAttribute('aria-pressed'), 'true'); assert.equal(reads.length, readCount);
  const d1Root = page.locator('[data-resource-kind=d1]'); assert.equal(await d1Root.evaluate(element => element.open), false);
  assert.match(await d1Root.locator(':scope > summary').textContent(), /7 GB \/ 10 GB/);
  assert.match(await d1Root.locator(':scope > summary').textContent(), /剩余 4 GB/);
  assert.match(await d1Root.locator(':scope > summary').textContent(), /超出 1 GB/);
  await open(d1Root); await open(group('d1')); await group('d1').locator(`[data-detail="${databaseOne}"]`).click();
  assert.equal(await page.locator('#resource-detail').textContent(), accountDetail, 'Both paths open the identical instance detail');
  await page.keyboard.press('Escape');
  for (const width of [1440, 960, 720, 390, 320]) {
    await page.setViewportSize({ width, height: 1000 });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, String(width));
    if ([1440, 390, 320].includes(width)) await page.screenshot({ path: join(directory, 'usage-resource-' + width + '.png'), fullPage: true });
  }
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.locator('#resource-view-account').click(); assert.equal(await group('d1').evaluate(element => element.open), true, 'Expansion state survives view switches');
  await open(group('r2')); await group('r2').getByRole('button', { name: '规划容量', exact: true }).click();
  await page.locator('#resource-budget-value').fill('10'); await page.locator('#resource-budget-save').click();
  await page.waitForFunction(() => !document.getElementById('resource-budget-dialog').open);
  assert.equal(await group('r2').locator('[data-budget]').evaluate(element => element === document.activeElement), true, 'Planning save restores the re-rendered trigger');
  assert.deepEqual(writes, ['budget']);
  assert.match(await group('r2').locator(':scope > summary [data-metric="r2/planning-storage"]').textContent(), /14 GB \/ 10 GB.*手工规划.*超出 4 GB/s);
  assert.equal(await group('r2').getByRole('button', { name: '用于部署', exact: true }).isEnabled(), true, 'Overage never disables deployment');
  await page.reload(); await ready(); assert.match(await group('r2').textContent(), /手工规划/);
  await page.locator('#resource-view-kind').click(); await open(page.locator('[data-resource-kind=r2]')); await open(group('r2'));
  await group('r2').getByRole('button', { name: '规划容量', exact: true }).click(); assert.equal(await page.locator('#resource-budget-value').inputValue(), '10');
  await page.locator('#resource-budget-clear').click(); await page.waitForFunction(() => !document.getElementById('resource-budget-dialog').open);
  assert.equal(await group('r2').locator('[data-budget]').evaluate(element => element === document.activeElement), true);
  assert.deepEqual(writes, ['budget', 'budget']); assert.equal(await page.locator('[data-metric="r2/planning-storage"]').count(), 0);
  state.usageDenied = true; await page.reload(); await ready();
  assert.match(await group('d1').locator(':scope > summary').textContent(), /— \/ —/);
  assert.match(await group('d1').textContent(), /用量未提供/); assert.equal(await group('d1').locator('[data-detail]').count(), 2);
  state.usageDenied = false; state.r2Denied = true; await page.reload(); await ready();
  assert.match(await group('r2', accountB).textContent(), /读取失败/); assert.match(await group('d1').textContent(), /6 GB \/ 5 GB/);
  assert.equal(await page.locator('.status-line').isVisible(), false);
  assert.deepEqual(writes, ['budget', 'budget']); assert.ok(!JSON.stringify(await page.content()).includes(fakeToken));
  token = 'invalid'; await page.evaluate(() => dispatchEvent(new PageTransitionEvent('pageshow', { persisted: true })));
  await page.getByText('身份验证失败，请重新登录', { exact: true }).waitFor();
  assert.equal(await page.locator('#resource-accounts').textContent(), '');
  assert.equal(await page.evaluate(() => localStorage.length + sessionStorage.length), 0); assert.deepEqual(errors, []);
  console.log('PASS UI-06: two views, collapsed parent totals, shared instances/quotas, account overage, manual planning persistence, unknowns, partial permissions, 5 widths and no deployment writes; synthetic providers');
} finally { await browser?.close(); await f.close(); }
