import test from 'node:test';
import assert from 'node:assert/strict';
import { signSession } from '../../cloud/access.mjs';
import { sbaDigest } from '../../cloud/sba-control.mjs';
import { zip } from '../sba-zip-fixture.mjs';
import { origin } from './admin-fixture.mjs';
import { sbaFixture as setup, policy, sha, sourceSha } from './sba-fixture.mjs';
test('authenticated preview → durable single dispatch → OIDC permit → verified artifact result', async t => {
  const x = await setup(t); assert.equal(x.adminState.sbaEnabled, true);
  assert.equal((await x.post('preview', { taskId: 'sba-test-task' }, { headers: {} })).status, 409);
  const plan = await x.preview(); assert.equal(x.state.dispatches, 0);
  assert.equal((await x.f.call('/api/admin/sba/state')).json().ready, true);
  const changed = structuredClone(plan); changed.plan.request.sourceSha = 'e'.repeat(40);
  assert.equal((await x.post('submit', changed)).status, 409);
  const forged = structuredClone(plan); forged.plan.manifest.actions.deploy.timeoutSeconds = 61;
  forged.confirmation = await signSession({ token: x.session, origin, actor: x.adminState.ownerId }, 'sba-confirm', [forged.plan, forged.expiresAt]);
  assert.equal((await x.post('submit', forged)).status, 409); assert.equal(x.state.dispatches, 0);
  const claims = await Promise.all([x.post('submit', plan), x.post('submit', plan)]);
  assert.ok(claims.every(r => r.status === 200)); assert.equal(x.state.dispatches, 1);
  await x.f.restart();
  assert.equal((await x.post('submit', plan)).status, 200); assert.equal(x.state.dispatches, 1);
  assert.equal((await x.permit(x.token({ workflow_sha: 'e'.repeat(40) }))).status, 403);
  x.state.badTitle = true; assert.equal((await x.permit()).status, 403); x.state.badTitle = false;
  assert.equal((await x.permit(x.token({ run_attempt: '2' }))).status, 403);
  const permits = await Promise.all([x.permit(), x.permit()]); assert.equal(permits.filter(r => r.status === 200).length, 1);
  const allowed = permits.find(r => r.status === 200).value;
  assert.deepEqual(allowed.secrets, { CLOUDFLARE_API_TOKEN: 'synthetic-deployment-secret' });
  assert.equal(allowed.requestDigest, await sbaDigest(allowed.request));
  assert.doesNotMatch((await x.f.call('/api/admin/sba/state')).text, /synthetic-deployment-secret|permitId|never-return/);
  await x.f.restart(); assert.equal((await x.permit()).status, 403);
  x.state.networkDown = true;
  assert.equal((await x.post('reconcile', { taskId: 'sba-test-task' })).status, 409);
  assert.equal((await x.f.call('/api/admin/sba/state')).json().job.status, 'running'); x.state.networkDown = false;
  const result = { schemaVersion: 2, taskId: allowed.request.taskId, action: 'deploy', sourceSha, applicationVersion: '1.0.0', status: 'succeeded', checks: [{ id: 'health-check', passed: true }] };
  x.state.archive = zip({ schemaVersion: 1, runId: 456, runAttempt: 1, executorSha: sha, requestDigest: allowed.requestDigest, permitId: allowed.permitId, result });
  x.state.runStatus = 'completed';
  assert.equal((await x.post('reconcile', { taskId: 'sba-test-task' })).json().job.status, 'succeeded');
  assert.equal((await x.post('reconcile', { taskId: 'sba-test-task' })).json().job.status, 'succeeded');
  assert.equal(x.state.dispatches, 1);
});
test('unknown dispatch can be bound by exact OIDC run without redispatch; machine host exposes no admin page', async t => {
  const x = await setup(t); x.state.dispatchLost = true;
  const plan = await x.preview(); assert.equal((await x.post('submit', plan)).json().job.status, 'dispatch-unknown');
  assert.equal((await x.post('submit', plan)).status, 200); assert.equal(x.state.dispatches, 1);
  assert.equal((await x.permit()).status, 200);
  for (const path of ['/', '/app.js', '/api/admin/state', '/node/poll'])
    assert.equal((await x.f.mf.dispatchFetch(policy.runnerOrigin + path)).status, 403);
  assert.equal((await x.permit(x.token(), undefined, origin + '/sba/v2/permit')).status, 403);
});
test('missing deployment secret rejects before permit consumption and disabled mode stays closed', async t => {
  const x = await setup(t, { SBA_APPLICATION_SECRETS: '{}' });
  const plan = await x.preview(); await x.post('submit', plan);
  assert.equal((await x.permit()).status, 403);
  assert.equal((await x.f.call('/api/admin/sba/state')).json().job.status, 'dispatched');
  const y = await setup(t, { ENABLE_SBA: 'no' }); assert.equal(y.adminState.sbaEnabled, false);
  assert.equal((await y.post('preview', { taskId: 'sba-test-task' })).status, 409);
  assert.equal((await y.permit()).status, 403); assert.equal(y.state.dispatches, 0);
});
